# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: http2nsupdate
email: http2nsupdate@myprs.de
description: > # this means to ignore newlines until "baseurl:"
        Do not reinvent the wheel! Doing DynDns style updates of your DNS Zone using
        all the existing infrastructure.
baseurl: "/http2nsupdate" # the subpath of your site, e.g. /blog
url: "http://www.mypersonalrocketscience.de" # the base hostname & protocol for your site
github_username:  myprs

# Build settings
markdown: kramdown
